@startuml


node "Load balancer" as lb
node "WebApp" as wb
node "Mobile app" as mb 
node "API" as api
database database as db

wb  -> lb 
mb  -> lb
api -> lb

node s_1 {

node "Local cache 1" as lc1
node "Server 1" as s1
lb  -> s1
s1  -> lc1 
}


node s_2 {

node "Server 2" as s2
node "Local cache 2" as lc2
lb  -> s2
s2  -> lc2
}
s1  -> db 
s2  -> db


@enduml